spring:
  datasource:
    url: jdbc:mysql://172.18.197.83:3306/gps_hisdata?useOldAliasMetadataBehavior=true&amp;autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=utf-8
    #url: jdbc:mysql://39.108.81.195:3306/gps_hisdata?useOldAliasMetadataBehavior=true&amp;autoReconnect=true&amp;useUnicode=true&amp;createDatabaseIfNotExist=true&amp;characterEncoding=utf-8
    username: jt808
    password: Adas@808.JT
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 5000
      min-idle: 5
      initial-size: 5

mybatis:
  typeAliasesPackage: com.aisafer.minasocket
  mapperLocations: classpath:mapper/*.xml

logging:
  file: logging
  level:
    com.aisafer.minisorket: error


