spring:
  datasource:
    url: jdbc:mysql://39.108.228.75:3306/gps_hisdata?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: Adastest
    password: Bd#$32%hbfScEv92381!#L
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
       max-idle: 10
       max-wait-millis: 60000
       min-idle: 5
       initial-size: 5
       time-between-eviction-runs-millis: 18800
       validation-query: SELECT 1
       test-on-borrow: false
       test-while-idle: true
       test-on-return: true
    tomcat:
      validation-query: SELECT 1

mybatis:
  typeAliasesPackage: com.aisafer.minasocket
  mapperLocations: classpath:mapper/*.xml

logging:
  file: logging
  level:
    com.aisafer.minisorket: error


